name: 'line-notify'

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: LINE Notify Actions
        uses: louis70109/line-notify-action@v0.2.0
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: 'LINE Notify test message'

